sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t connieruth/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true connieruth/docker-react npm run test
